# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_gpt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63hat_gpt.proto\"\x1d\n\x0b\x43hatRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\" \n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t27\n\x07\x43hatGPT\x12,\n\x0b\x43hatWithGPT\x12\x0c.ChatRequest\x1a\r.ChatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_gpt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATREQUEST']._serialized_start=18
  _globals['_CHATREQUEST']._serialized_end=47
  _globals['_CHATRESPONSE']._serialized_start=49
  _globals['_CHATRESPONSE']._serialized_end=81
  _globals['_CHATGPT']._serialized_start=83
  _globals['_CHATGPT']._serialized_end=138
# @@protoc_insertion_point(module_scope)
